export const metadata = {
  title: 'Privacy Policy — Social Media Dost',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50 px-4 py-12">
      <div className="max-w-3xl mx-auto bg-white rounded-xl border border-gray-200 p-8 space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Privacy Policy</h1>
          <p className="text-gray-500 text-sm mt-1">Social Media Dost — operated by Niranjan Enterprises Digital Solutions</p>
        </div>

        <Section title="Who we are">
          <p>Social Media Dost (this application, at socialmediadost.com) is operated by Niranjan Enterprises Digital Solutions as an internal content-production tool used to plan, generate, review, and approve social media and advertising content on behalf of our clients.</p>
        </Section>

        <Section title="Information we collect">
          <p>We collect and store:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Account information</strong> — name, email address, and role, for staff accounts and for client contacts given access to the client approval portal.</li>
            <li><strong>Client business information</strong> — brand details, target audience, and content preferences that staff enter to guide content generation for that client.</li>
            <li><strong>Content and campaign material</strong> — briefs, generated captions, images, video, and ad copy created within the platform, plus any comments or feedback left during review.</li>
            <li><strong>Usage and technical data</strong> — standard server logs (IP address, browser type, timestamps) generated by normal operation of the application.</li>
          </ul>
        </Section>

        <Section title="How we use this information">
          <p>Information is used solely to operate the platform: to generate and manage content on behalf of a client, to let staff and client contacts review and approve that content, and to maintain the security and reliability of the service.</p>
          <p>Content generation is powered by Anthropic&apos;s Claude API (text) and by Cloudinary, Replicate, and Runway (image/video generation). Brief and client details relevant to a specific generation request are sent to these providers to produce that content; they are not used by us for any purpose beyond fulfilling the request.</p>
          <p>We do not sell or rent any information collected through this platform to any third party.</p>
        </Section>

        <Section title="Sharing with connected Niranjan Enterprises systems">
          <p>Social Media Dost is one part of a small set of internal systems Niranjan Enterprises Digital Solutions operates for its own clients (alongside our CRM and service-delivery platforms). Client and content information may be shared automatically between these systems — for example, an approved brief may be linked to a client record in our CRM, or approved content may be scheduled through our service-delivery platform — solely to avoid re-entering the same information twice. None of this data is shared outside this group of internally-operated systems.</p>
        </Section>

        <Section title="Meta / Facebook integration">
          <p>Where enabled, staff may push an approved ad creative (text and call-to-action only) directly into our own Meta advertising account&apos;s creative library, so it can be used to build a campaign without retyping it. This integration only ever creates a creative asset — it does not create, modify, or launch a campaign, and it does not touch advertising budgets or audience targeting. It is restricted to our own advertising account and is never used to access or modify a third party&apos;s Meta account or data.</p>
        </Section>

        <Section title="Data security">
          <p>Access to the platform requires an authenticated account, and access is scoped by role — a client contact can only see their own organization&apos;s content. Data is transmitted over encrypted (HTTPS) connections. We take reasonable precautions to protect stored information from unauthorized access.</p>
        </Section>

        <Section title="Your rights">
          <p>If you are a client contact or staff member with an account on this platform, you may request to see what information we hold about you, request a correction, or request deletion of your account and associated personal data, by contacting us using the details below.</p>
        </Section>

        <Section title="Contact us">
          <p>Niranjan Enterprises Digital Solutions<br />
          2nd Floor, 657, Rangrekha Apartment, Near Kunjir Talim, Sadashiv Peth, Pune 411030<br />
          Email: <a href="mailto:contact@niranjanenterprises.com" className="text-blue-600 hover:underline">contact@niranjanenterprises.com</a><br />
          Phone: +91 92205 18202</p>
        </Section>

        <p className="text-xs text-gray-400 pt-4 border-t border-gray-100">Last updated: August 2026.</p>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-2">
      <h2 className="text-base font-semibold text-gray-900">{title}</h2>
      <div className="text-sm text-gray-600 leading-relaxed space-y-2">{children}</div>
    </div>
  )
}
